plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.116'
}

version = mod_version
group = mod_group_id

repositories {
    maven { url = "https://maven.createmod.net" } // Репозиторий для Create, Ponder и Flywheel
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
}





base {
    archivesName = mod_id
}

// NeoForge 1.21.1 требует Java 21
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

// Default run configurations.
runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    
    // Подключаем Create и новую версию Ponder локально из папки libs
    implementation files("libs/create-1.21.1-6.0.10.jar")
    implementation files("libs/ponder-neoforge-1.0.84+mc1.21.1.jar")
}











// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// Официальный и 100% рабочий способ копирования для NeoForge
tasks.register('deployMod', Copy) {
    dependsOn 'jar' // Дожидаемся окончания сборки архива
    
    // Вместо угадывания папки "build/libs", берем точный файл из системных тасок Gradle
    from tasks.named('jar').flatMap { it.archiveFile }
    
    // Путь к папке модов в твоем Prism Launcher
    into "C:/Users/qwer/AppData/Roaming/.ElyPrismLauncher/instances/modtest/.minecraft/mods"
}
