# Версии игры и загрузчика
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.65
neo_version_range=[21.1.65,21.2)
loader_version_range=[4,)

# Данные вашего мода (можете изменить потом)
mod_id=create_addon
mod_name=Create: Getting Hot
mod_license=MIT
mod_version=1.0.2
mod_group_id=com.example.createaddon
mod_authors=Nuclear28, Google Gemini
mod_description=A new HOT mod
pack_format_number=34
#ponder_version=1.0.82


# Настройки Java
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

